//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsertComShop
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class products
    {
        public int pid { get; set; }
        public string name { get; set; }
        [StringLength(Int32.MaxValue)]
        public string detail { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> amount { get; set; }
        public string image { get; set; }
        public string type { get; set; }
        public string product_id { get; set; }
    }
}
