//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.boxsetItems = new HashSet<boxsetItems>();
            this.orderItems = new HashSet<orderItems>();
        }
    
        public int pid { get; set; }
        public string name { get; set; }
        public string detail { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> amount { get; set; }
        public string image { get; set; }
        public string type { get; set; }
        public string product_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boxsetItems> boxsetItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderItems> orderItems { get; set; }
    }
}
